from flask import Flask, flash, request, redirect, url_for
from os.path import join, dirname, realpath
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from os import path
import os


db = SQLAlchemy()                         # Using SQLAlchemy as our database engine of this project.
DB_NAME = "database.db"                   # Filename and location of the database.
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'docx', 'doc'} # Allowed file extensions to be uploaded.
UPLOAD_FOLDER = join(dirname(realpath(__file__)), 'static/img/')

                                          # Email authorized to directly run debugging functionalities.
ADMIN = "kristian.paivinen@yahoo.com"     # Disable for additional security.
SIGNUP_ENABLED = True                     # Disable if you do not want signup to be accessible.

MIN_NUMER_FILEGENERATOR = 100000
MAX_NUMBER_FILEGENERATION = 999999        # Useful to set higher in order to increase randomness.

GENERATED_OUTPUT_DIRECTORY = 'generated/' # Directory where everything generated by the application will be located.
SUBDOMAIN_SCAN_OUTPUT_DIRECTORY = join(dirname(realpath(__file__)), GENERATED_OUTPUT_DIRECTORY, 'subdomains/')
PORT_SCAN_OUTPUT_DIRECTORY = join(dirname(realpath(__file__)), GENERATED_OUTPUT_DIRECTORY, 'ports/')
VULNERABILITY_SCAN_OUTPUT_DIRECTORY = join(dirname(realpath(__file__)), GENERATED_OUTPUT_DIRECTORY, 'vulnerabilities/')



def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs' # Change secret key in order to mitigate serious vulnerability
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app)
 

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')
